server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-management
    driver-class-name: com.mysql.jdbc.Driver
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: password
debug: false
